#!/usr/bin/env bash
# Indefinitely writes "I am alive" to the file /tmp/my_process.
#   Pauses two seconds in between each message.

for (( i=0; i>=0; i++ ))
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
