#!/usr/bin/env bash
# This cript that displaying  Best School 10 times,
# but for the 9th iteration, displays Best School and then Hi on a new line.
i=1
while [ "${i}" -le 10 ]
do
if [ "${i}" -eq 9 ];
then
echo 'Hi';
else
echo 'Best School'
fi
((i++))
done
